### ISSUE TITLE
Area code filtering not working for me

### ISSUE THREAD

**Issue by atbaker** [TwilioDevEd/call-tracking-rails#1]
The area code filtering doesn't seem to be working. When I type in "415" in the form on the homepage, I expect to see all the phone numbers on the next page start with "(415)":

http://localhost:3000/available_phone_numbers?area-code=415

![image](https://cloud.githubusercontent.com/assets/826669/9857264/8c118630-5ae7-11e5-8ce7-b2e1e205ce07.png)

Right now it seems like it's giving me a mostly random list of available phone numbers.

**Comment by acamino** [comment]
@atbaker would you mind reviewing this PR #3.

**Comment by atbaker** [comment]
That PR did the trick! Closing this issue.
