### ISSUE TITLE
Missing helper file

### ISSUE THREAD

**Issue by neetso** [TwilioDevEd/call-tracking-rails#5]
Trying to run the rails code but experiencing the following error when running rspec (or the server):

/Users/mnsteen/.rvm/gems/ruby-2.2.3@twiliodeved/gems/actionpack-4.2.0/lib/abstract_controller/helpers.rb:151:in `rescue in block in modules_for_helpers': Missing helper file helpers//users/mnsteen/code/hallometrics/twilio_dev_ed/call_tracking_rails/app/helpers/application_helper.rb_helper.rb (AbstractController::Helpers::MissingHelperError)

**Comment by neetso** [comment]
Seems to be an issue with ruby 2.2.3, got app working with 2.1.5 (for example), so closing...

**Comment by acamino** [comment]
@neetso thanks for letting us know.
